config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' , registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :movies do
    get '/', action: :index
    post '/', action: :index
    get '/show/:id', action: :show, as: 'show'
    post '/seen', action: :seen
    post '/unseen', action: :unseen
    post '/rate', action: :rate
  end

  namespace :lists do
    get '/', action: :index
    post '/', action: :index
    get '/show/:id', action: :show, as: 'show'
    post '/new', action: :new
    post '/addTo', action: :add_to
    delete '/:id', action: :delete, as: 'delete'
  end

  namespace :users do
    get '/profile', action: :profile
  end

  namespace :recommendations do
    get '/', action: :index
    get '/check', action: :check_recommendations
    post '/rate', action: :rate
  end

  root to: 'main#index'
end

app/models/list.rb
class List
  include Mongoid::Document

  belongs_to :user
  has_and_belongs_to_many :movies

  field :title, type: String
  field :description, type: String
end

app/controllers/lists_controller.rb
require 'will_paginate/array'

class ListsController < ApplicationController

	def index
		@query = params[:query]

    if @query
			@type = "query"
			@lists = List.where(title: /#{@query}/)
      @total_records = @lists.count
		else
			@lists = List.all.shuffle.paginate(:page => params[:page], :per_page => 10)
		end
	end

  def show
    @list = List.find(params[:id])

  end

	def new
		@list = List.new
		@list.title = params[:title]
		@list.description = params[:description]
		@list.user = current_user

		respond_to do |format|
			if @list.save!
	      format.json { render json: { status: :success, message: 'Lista adicionada com sucesso!', id: @list.id } }
			else
	      format.json { render json: { status: :error, message: 'Erro ao salvar lista!'}}
	    end
    end
	end

	def add_to
		@list = List.find(params[:list_id])
		@movie = Movie.find(params[:movie_id])

    @list.movies << @movie unless @list.movies.include?(@movie)

		respond_to do |format|
			if @list.save!
	      format.json { render json: { status: :success, message: 'Filme adicionado a lista!'} }
			else
	      format.json { render json: { status: :error, message: 'Erro ao adicionar filme!'}}
	    end
    end
	end

	def delete
    puts "AQUIIIIIIII"
		@list = List.find(params[:id])
		respond_to do |format|
			if @list.destroy!
				format.json { render json: { status: :success, message: 'Lista removida com sucesso!'} }
			else
				format.json { render json: { status: :error, message: 'Erro ao remover lista!'}}
			end
		end
	end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/index.html.erb
<div class="container">
  <%= form_tag(lists_path, method: :post, class: "col s12 center-align") do%>
    <h4> Busca de Listas </h4>
    <div class="row">
      <div class="input-field col s6 offset-s3">
        <%= text_field_tag :query,@query, placeholder: 'Digite termo para pesquisa', required: true, class: 'validate'%>
      </div>
      <div class="input-field col s2">
        <%= button_tag class: 'btn' do %>
          <i class="fa fa-search"></i>
        <% end %>
        <% if @type == "query" %>
          <a href="/lists" class="btn"><i class="fa fa-ban"></i></a>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

  <div class="container">
    <div class="col s12 center-align">
        <% if @type == "query" %>
          <h5> Resultados da Busca </h5> <h6>(<%= @total_records rescue 0 %> listas encontradas) </h6>
        <% else %>
          <h5> Listas </h5>
        <% end %>
        <% if not @lists.empty? %>
      <%= will_paginate @lists %>
      <div class="row">
          <% @lists.each_with_index do |list, index|%>
            <div class="col s4 m2">
              <div class="card hoverable">
                <div id="content-<%= list.id %>" class="card-image waves-effect waves-block waves-light">
                  <% if list.movies.empty?%>
                    <%= image_tag 'indisponivel.jpg', class: 'img-responsive activator'%>
                  <% else %>
                    <div class="row">
                    <% list.movies[0..1].each do |movie|%>
                      <div class="col s6">
                        <%= image_tag (movie.image ? movie.image : 'indisponivel.jpg'), class: 'img-responsive activator'%>
                      </div>
                    <% end %>
                    </div>
                    <% if list.movies.length > 2 %>
                    <div class="row">
                    <% list.movies[2..3].each do |movie|%>
                      <div class="col s6">
                        <%= image_tag (movie.image ? movie.image : 'indisponivel.jpg'), class: 'img-responsive activator'%>
                      </div>
                    <% end %>
                    </div>
                    <% end %>
                  <% end %>
                </div>
                <div class="card-content">
                  <span class="activator"><i><%= list.title %></i></span>
                  <span class="activator">Por <%= list.user.name %></span>
                </div>
                <div class="card-action">
                  <a href="<%= lists_show_path(list)%>" class=" action"> Ver</a>
                </div>
              </div>
            </div>
            <% if (index + 1) % 6 == 0%>
              </div>
              <div class="row">
            <% end %>
          <% end %>
      </div>
      <% end %>
    </div>
  </div>

app/views/lists/show.html.erb
<% content_for :title, "Movist | #{@list.title}" %>

<div class="container">
  <div class="row">
    <div class="col s12 m12">
      <div class="card horizontal hoverable">
        <div class="card-content" style="width: 100%">
          <span class="card-title center-align">
            <%= @list.title %> <br/>
          </span>

          <div class="row">
            <div class="col s12 m12">
              <p style="text-align: justify;"> <b>Author: </b> <%= @list.user.name %> </p>
            </div>
          </div>

          <div class="row">
            <div class="col s12 m12">
              <p style="text-align: justify;"> <b>Descrição: </b> <%= @list.description %> </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m12">
      <div class="card horizontal hoverable">
        <div class="card-content" style="width: 100%">
          <span class="card-title ">
            Filmes

            <% if @list.user == current_user %>
            <div class="right">
              <a href="<%= movies_path%>" class="btn"> Adicionar Filmes </a>
            </div>
            <% end %>
          </span>
          <div class="row">
            <div class="col s12 m12">
              <div>
                <div class="row">
                  <% @list.movies.each_with_index do |movie, index| %>
                      <div class="col s3">
                        <div class="card hoverable">
                          <div id="content-<%= movie.id %>" class="card-image waves-effect waves-block waves-light">
                            <%= image_tag (movie.image ? movie.image : 'indisponivel.jpg'), class: 'img-responsive' %>
                            <% if movie.users.include?(current_user) %>
                                <i class="seen circle fa fa-check light-green accent-2 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Visto"></i>
                            <% end %>
                          </div>
                          <div class="card-content">
                            <span><%= movie.title %></span>
                          </div>
                          <div class="card-reveal" style="text-align: left !important;">
                            <span class="card-title"><%= movie.title %>
                              <i class="material-icons small right">close</i></span>
                            <p> <%= movie.overview %></p>
                            <a href="<%= movies_show_path(movie) %>" class="btn"> Ver Mais </a>
                          </div>
                          <div class="card-action">
                            <a class="dropdown-button" href="#!" data-activates="dropdown<%= index %>" data-constrainwidth="false">
                              Ações </a>

                            <ul id="dropdown<%= index %>" class="dropdown-content z-index-4" style="width: 300px !important;">
                              <li><a href="<%= movies_show_path(movie) %>" class="yellow-text text-darken-2">
                                <i class="fa fa-share"></i> Ver Info </a></li>
                              <% if movie.users.include?(current_user) %>
                                  <li>
                                    <a onclick="markAsUnseen('<%= movie.id %>')" class="yellow-text text-darken-2"><i class="fa fa-check"></i>
                                      Marcar como não visto</a></li>
                              <% end %>
                              <% if not movie.users.include?(current_user) %>
                                  <li>
                                    <a onclick="markAsSeen('<%= movie.id %>')" class="yellow-text text-darken-2"><i class="fa fa-check"></i>
                                      Marcar como visto</a></li>
                              <% end %>
                              <li>
                                <a href="#modal-list-add" onclick="setMovieID('<%= movie.id %>')" class="yellow-text text-darken-2"><i class="fa fa-plus"></i>
                                  Adicionar a uma lista</a></li>
                              <li>
                                <a href="#modal-rating" onclick="setMovieID('<%= movie.id %>')" class="yellow-text text-darken-2"><i class="fa fa-star"></i>
                                  Dar nota</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <% if (index + 1) % 4 == 0 %>
                          </div>
                          <div class="row">
                      <% end %>
                  <% end %>
                  </div>
                  </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>