config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' , registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :movies do
    get '/', action: :index
    post '/', action: :index
    get '/show/:id', action: :show, as: 'show'
    post '/seen', action: :seen
    post '/unseen', action: :unseen
    post '/rate', action: :rate
  end

  namespace :lists do
    get '/', action: :index
    post '/', action: :index
    get '/show/:id', action: :show, as: 'show'
    post '/new', action: :new
    post '/addTo', action: :add_to
    delete '/:id', action: :delete, as: 'delete'
  end

  namespace :users do
    get '/profile', action: :profile
  end

  namespace :recommendations do
    get '/', action: :index
    get '/check', action: :check_recommendations
    post '/rate', action: :rate
  end

  root to: 'main#index'
end

app/models/recommendation.rb
class Recommendation
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :recommendation_set
  belongs_to :movie


  field :like, type: Boolean
  rateable range: (1..10), raters: User
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @set = current_user.recommendation_sets[-1] if current_user
  end

  def check_recommendations

    if current_user.likes_count + current_user.dislikes_count < 10
      flash[:alert] = "Avalie mais filmes para ter uma recomendação melhor (minimo de 10)"
      redirect_to recommendations_path and return
    end

    Recommendable::Helpers::Calculations.update_similarities_for(current_user.id)
    Recommendable::Helpers::Calculations.update_recommendations_for(current_user.id)

    @rec_set = RecommendationSet.new
    @rec_set.user = current_user
    @rec_set.save!

    @movies = current_user.recommended_movies[0..20]
    @movies.each do |movie|
      r = Recommendation.new
      r.movie = movie
      r.recommendation_set = @rec_set
      r.save!
    end



    redirect_to recommendations_path
  end

  def rate
    @recommendation = Recommendation.find(params[:id])
    @rate = params[:rate].to_i

    @recommendation.rate @rate, current_user unless @recommendation.rated_by? current_user
    @recommendation.like = @rate >= 6

    @movie = @recommendation.movie
    @movie.rate @rate, current_user unless @movie.rated_by? current_user

    current_user.like(@movie) if @rate.to_i >= 6
    current_user.dislike(@movie) if @rate.to_i < 6

    respond_to do |format|
      if @recommendation.save!
        format.json { render json: { status: :success, message: 'Avaliação salva com sucesso!'}}
      else
        format.json { render json: { status: :error, message: 'Erro ao salvar avaliação!' } }
      end
    end
  end
end

app/views/recommendations/index.html.erb
<% content_for :title, "Movist | Recomendações" %>

<div class="container">
  <div class="row">
    <div class="col s12 m12">
      <div class="card horizontal hoverable">
        <div class="card-content" style="width: 100%">
          <div class="card-title">
            Filmes Recomendados

            <div class="right">
              <a href="<%= recommendations_check_path %>" class="btn"> Atualizar Recomendações </a>
            </div>
          </div>
          <% unless @set.nil? %>
          <div class="row">
            <% @set.recommendations.each_with_index do |rec, index| %>
                <div class="col s4 m2">
                  <div class="card hoverable">
                    <div id="content-<%= rec.id %>" class="card-image waves-effect waves-block waves-light">
                      <%= image_tag (rec.movie.image ? rec.movie.image : 'indisponivel.jpg'), class: 'img-responsive' %>
                      <% if rec.like %>
                        <i class="seen circle fa fa-thumbs-up light-green accent-2 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Gostou"></i>
                      <% else %>
                        <i class="seen circle fa fa-thumbs-down light-red accent-2 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Não Gostou"></i>
                      <% end %>
                    </div>
                    <div class="card-content">
                      <span><%= rec.movie.title %></span>
                    </div>
                    <div class="card-reveal" style="text-align: left !important;">
                        <span class="card-title"><%= rec.movie.title %>
                          <i class="material-icons small right">close</i></span>
                      <p> <%= rec.movie.overview %></p>
                      <a href="<%= movies_show_path(rec.movie) %>" class="btn"> Ver Mais </a>
                    </div>
                    <div class="card-action">
                      <a href="<%= movies_show_path(rec.movie) %>" class="yellow-text text-darken-2">
                        Ver Info </a>
                      <a onclick="setRecID('<%= rec.id %>');$('#modal-rating-recommendations').modal('open')" class="yellow-text text-darken-2 modal-trigger"> Gostou? </a>
                    </div>
                  </div>
                </div>
                <% if (index + 1) % 6 == 0 %>
                    </div>
                    <div class="row">
                <% end %>
            <% end %>
          </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>